tap "buo/cask-upgrade"
tap "jesseduffield/lazygit"
tap "nikitabobko/tap"

brew "bash"
brew "bash-completion"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "fzf"
brew "gh"
brew "go"
brew "htop"
brew "jq"
brew "kubernetes-cli"
brew "lima"
brew "mas"
brew "mise"
brew "neovim"
brew "node"
brew "ripgrep"
brew "starship"
brew "stow"
brew "yq"
brew "zoxide"
brew "jesseduffield/lazygit/lazygit"

cask "bambu-studio"
cask "datagrip"
cask "firefox@beta"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "legcord"
cask "libreoffice"
cask "rectangle"
cask "spotify"
cask "zed"

mas "AdGuard for Safari", id: 1440147259
mas "Bitwarden", id: 1352778147
mas "Refined GitHub", id: 1519867270

if File.exist?(File.expand_path("~/.work"))
    brew "libpq", link: true
    mas "Slack", id: 803453959
end

if File.exist?(File.expand_path("~/.personal"))
    tap "LizardByte/homebrew"
    brew "sunshine"
    mas "Photomator", id: 1444636541
end

